### ISSUE TITLE
API Docs for this Library

### ISSUE THREAD

**Issue by tmountain** [googleapis/python-videointelligence#430]
Where is the actual API documentation for this library? The docs provided give minimal information (Quickstart, Installation, etc). The link for "Client Library Documentation" just points to the same page. I just want to browse the methods this library exposes with basic descriptions of what they provide.

**Comment by suztomo** [comment]
Sorry for late response. API reference is available in https://cloud.google.com/python/docs/reference/videointelligence/latest.
